name: Security Scan
# Se ejecuta cuando haces push o pull request
on: [push, pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Importante: Descarga todo el historial para escanearlo

      - name: GitGuardian Scan
        uses: GitGuardian/ggshield-action@master
        env:
          # Esta variable la configuras despuÃ©s en la web de GitHub (Settings > Secrets)
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}